### ISSUE TITLE
Unable to get working

### ISSUE THREAD

**Issue by raisonon** [carldanley/diffbot#1]
Get the following from vagrant up: 

==> default: stdin: is not a tty
==> default: ERROR! Unexpected Exception: No module named markupsafe

==> default: ImportError: No module named markupsafe
==> default: nginx: unrecognized service

I get the virtual session loaded but cannot access the site on ip or host. I get: refused to connect.

Any ideas? Or perhaps you could share the actual plugin folder?

Many thanks

**Comment by carldanley** [comment]
Are you running `vagrant up` from the root folder of this project? I believe the [`wp-plugins.yml`](https://github.com/carldanley/diffbot/blob/master/ansible/wp-plugins.yml) is not needed and was accidentally committed.

**Comment by raisonon** [comment]
Hi Carl - I got working in the end by reinstalling node (a few times). Unsure the problem, but got it in the end. Thanks for replying in any case!
